<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <ul>
            <!-- First page link -->
            <li>
                <a href="<?php echo $this->url($this->route); ?>?page=1">
                    <<
                </a>
            </li>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                        <
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                        >
                    </a>
                </li>
            <?php endif; ?>
            <!-- Last page link -->
            <li>
                <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->pageCount; ?>">
                    >>
                </a>
            </li>
        </ul>
    </div>
<?php endif; ?>