<?php
$title = 'Uprava produktu';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('product', array('action' => 'edit', 'id' => $this->id,)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nazov'));
echo $this->formRow($form->get('kod'));
echo $this->formRow($form->get('ean'));
echo $this->formRow($form->get('sklad'));
echo $this->formRow($form->get('cena'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();